# Generated by Django 5.0 on 2026-02-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('additional_links', models.TextField(blank=True)),
                ('isPrivate', models.BooleanField(default=False)),
                ('currentLocation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='jobsAppliedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Review', 'Review'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('jobIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('jobSeekerIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
            ],
        ),
    ]
