# Generated by Django 5.0 on 2026-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(help_text=None, max_length=100),
        ),
    ]
