# Generated by Django 5.0 on 2026-02-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_jobseeker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
