# Generated by Django 5.0 on 2026-02-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salaryLower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaryUpper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isRemote', models.BooleanField(default=False)),
                ('hasVisaSponsorship', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
